import { readFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, test } from 'vitest'
import { LOCALES } from '../i18n/translations'
import { CHART_BASENAME, CHART_WIDTH, CHART_HEIGHT, chartPng, chartPdf } from '../content/chart'

// The chart is generated by `node scripts/render-alphabet-chart.mjs` and the
// outputs are committed, so nothing at build time regenerates them. These
// assertions are what stands between a rename and a 404 on the page.
const pub = (p: string) => resolve(__dirname, '../../public', p.replace(/^\//, ''))

describe('chart assets', () => {
  test('every locale has a PNG and a PDF on disk', () => {
    for (const locale of LOCALES) {
      expect(existsSync(pub(chartPng(locale))), `missing ${chartPng(locale)}`).toBe(true)
      expect(existsSync(pub(chartPdf(locale))), `missing ${chartPdf(locale)}`).toBe(true)
    }
  })

  test('declared dimensions match the real PNG header', () => {
    // PNG IHDR: 8-byte signature, 4-byte length, 4-byte "IHDR", then width and
    // height as big-endian uint32.
    for (const locale of LOCALES) {
      const buf = readFileSync(pub(chartPng(locale)))
      expect(buf.subarray(12, 16).toString('ascii')).toBe('IHDR')
      expect([buf.readUInt32BE(16), buf.readUInt32BE(20)], `${chartPng(locale)} is the wrong size`).toEqual([
        CHART_WIDTH,
        CHART_HEIGHT,
      ])
    }
  })

  test('the PDFs are real PDFs', () => {
    for (const locale of LOCALES) {
      expect(readFileSync(pub(chartPdf(locale))).subarray(0, 5).toString('ascii')).toBe('%PDF-')
    }
  })

  test('basenames stay lowercase, hyphenated and free of locale collisions', () => {
    const names = Object.values(CHART_BASENAME)
    for (const name of names) expect(name).toMatch(/^[a-z0-9-]+$/)
    expect(new Set(names).size).toBe(names.length)
  })
})
