#!/usr/bin/env node
/**
 * Vendors the web fonts into apps/web/public/fonts and regenerates
 * apps/web/src/styles/fonts.css.
 *
 * Why: loading these from fonts.googleapis.com cost 1,056 ms of render
 * blocking plus 466 ms of connection setup on mobile — the whole gap
 * between a 120 ms server response and a 4.5 s First Contentful Paint.
 * Same origin means no extra DNS, TLS or round trip.
 *
 * Re-run when a font is added or Google ships a new version:
 *   node scripts/vendor-fonts.mjs
 *
 * Both families are SIL Open Font License 1.1, which permits self-hosting.
 */
import { writeFile, mkdir } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'apps/web/public/fonts')
const CSS_OUT = join(ROOT, 'apps/web/src/styles/fonts.css')

const SRC = 'https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500&display=swap'

// Uzbek Latin needs latin-ext (ş ç ğ ö); the converter's input side and the
// Russian pages need cyrillic. greek, greek-ext, cyrillic-ext and vietnamese
// are dead weight for this site.
const KEEP = new Set(['latin', 'latin-ext', 'cyrillic'])

// A modern desktop UA is required or Google serves TTF instead of WOFF2.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

const css = await fetch(SRC, { headers: { 'User-Agent': UA } }).then((r) => r.text())

/** Split the stylesheet into `/* subset *\/ @font-face { ... }` pairs. */
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face \{[^}]+\})/g)].map(
  ([, subset, rule]) => ({ subset, rule }),
)

await mkdir(OUT_DIR, { recursive: true })

const out = []
let bytes = 0

for (const { subset, rule } of blocks) {
  if (!KEEP.has(subset)) continue

  const family = /font-family: '([^']+)'/.exec(rule)[1]
  const style = /font-style: (\w+)/.exec(rule)[1]
  const weight = /font-weight: (\d+)/.exec(rule)[1]
  const url = /src: url\((https:[^)]+)\)/.exec(rule)[1]

  const slug = family.toLowerCase().replace(/\s+/g, '-')
  const name = `${slug}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`

  const buf = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()))
  await writeFile(join(OUT_DIR, name), buf)
  bytes += buf.byteLength
  console.log(`  ${String(Math.round(buf.byteLength / 1024)).padStart(4)} KB  ${name}`)

  out.push(rule.replace(url, `/fonts/${name}`).replace(/^@font-face \{/, '@font-face {').trim())
}

const header = `/* Generated by scripts/vendor-fonts.mjs — do not edit by hand.
   Self-hosted so the first paint never waits on fonts.googleapis.com.
   Inter and Instrument Serif are SIL Open Font License 1.1. */\n\n`

await writeFile(CSS_OUT, header + out.join('\n\n') + '\n')
console.log(`\n${out.length} faces, ${Math.round(bytes / 1024)} KB total -> apps/web/public/fonts`)
